markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : LeenBlogging
production_url : http://weileen.me
description: "Words & projects by Ng Wei Leen. Inbound Marketing, Distribution Hacking & Startups"
disqus_shortname: leenblogging
analytics: UA-31319100-1
facebook: 227701109
author :
  name : Ng Wei Leen
  github : plen
  twitter : ngweileen
  email: plen@weileen.me
